language: php
php:
  - "5.5"


install:
  - composer install

script:
  - phpunit
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover